### PR TITLE
Add next.js typescript example

### PR DESCRIPTION
**Pull request by kylemh**
See: https://github.com/bahmutov/next-and-cypress-example/issues/104

### CODE REVIEW

**Comment by kylemh** [comment]
The CLA assistant doesnt seem to work for me

**Comment by kylemh** [comment]
The one thing I'd like help on and could not get working would be automatic path aliasing. Out of the box, Next.js TS has root-folder path aliases. Additionally, if I define any in the root `tsconfig.json`, I'd love for them to persist to Cypress.

Ignoring the feature request-y nature of the above. I couldn't get path aliases even explicitly working if they collided with a path alias from the root.

**Review by bahmutov — APPROVED** [review]
I love this. You know what you could do in your example README - take a screenshot of the coverage report showing the filenames, similar to https://github.com/bahmutov/next-and-cypress-example#coverage

**Comment by bahmutov** [comment]
No, currently have no idea how to do it

**Comment by kylemh** [comment]
Done! Resolved a few small issues as well. Please note, I had no need for `cypress/tsconfig.json`!

I'l also willing and able to merge this in as a 1st-class solution if you'd like

**Comment by bahmutov** [comment]
What do you mean as 1st class solution?

**Comment by kylemh** [comment]
hahaha sorry.. i mean it doesn't have to be external (tied to my github account).

We could put into the official examples folder of this repo

**Pull request merged**
