### PR TITLE
feature: Allow multiple backend processes with urls config

### LINKED ISSUE #349: Allow multiple backend processes with urls config
Our system consists of multiple micro-service backend processes which we would like to collect all the coverage from.

We would like to have a way to configure the plugin to collect coverage information from multiple URLs and save that out.

While we could try to collect that coverage out of band, it makes more sense to leverage the  infrastructure already in place to do so.

### PR DESCRIPTION
**Pull request by nickpalmer**
Fixes #349

### CODE REVIEW

**Review by bahmutov — CHANGES_REQUESTED** [review]
I would love to have an issue for this PR with description, and an example in the examples folder to validate it is working.

Also, I think a better / simpler solution would be to just allow the `url` parameter to accept multiple URLs comma-separated

```json
{
  "env": {
    "codeCoverage": {
      "url": "http://localhost:3000/__coverage__, http://localhost:8080/__coverage__"
    }
  }
}
```

**Comment by nickpalmer** [comment]
The only issue with using commas I can think of is if somebody needs a comma in the URI for some weird reason. I will try to find time to add an example soon.

**Comment by jennifer-shehane** [comment]
@nickpalmer Do you still have time to address the changes requested in this PR? We will have to close this PR due to inactivity otherwise.

**Comment by nickpalmer** [comment]
Sorry, super busy lately, but I will update the PR with review feedback next week.

**Comment by truxiced** [comment]
This is a nice feature, would love to have it in our project. 
Is this far out from a release ?

**Pull request closed without merging**
