### PR TITLE
Save coverage for each page in a test

### LINKED ISSUE #69: Saving coverage before page changes in test
From my understanding, currently this plugin will only save coverage at the end of the test. Since coverage is stored on the `window`, if you have a test that navigates across more pages where `window` gets replaced, only the coverage from the last `window` will get saved even though different could could have been executed in the previous pages. I would like to collect coverage from every part of the app that was executed in the test.

As a workaround, I can manually save coverage using the `combineCoverage` task in my test when I think I am done with executing the current page and I expect the next interaction to cause the page to change. However, this is less than ideal because it is an implementation detail that interrupts the flow of the test. It may be possible that I would also miss some coverage with this approach on something like additional form submission logic.

I have attempted to add a binding to the Cypress window events described here: https://docs.cypress.io/api/events/catalog-of-events.html#Binding-to-Events

However that generates an error about returning a promise inside a promise, so I'm not sure if it's possible to use `cy.task()` or `combineCoverage` in particular with a Cypress event listener.

Does anyone have an idea how saving coverage before a page could be automated? If it's possible, would that be a feature that could be added to this plugin?

Thank you for the work on this plugin, I find it very useful!

### PR DESCRIPTION
**Pull request by grantbdev**
Save coverage for each page visited in a test by keeping a reference to the coverage for each app window loaded and then saving the coverage at the end after coverage is calculated.

The implementation in the PR keeps the behavior of saving coverage after each test since that is the current behavior and I believe it would be necessary for #4. However, I think it would also be possible to initialize the array and event listener in `before()` and only save coverage in `after()` if that is desired instead.

Closes #69

### CODE REVIEW

**Comment by bahmutov** [comment]
Hmm, @grantbdev I love it. I just need an example site showing this in action.

**Comment by grantbdev** [comment]
@bahmutov I can do that. Do you have any preferences on what I base it on or is any minimum repo that has different JS (be it jQuery, React, etc.) loaded/executed across windows sufficient?

**Comment by grantbdev** [comment]
@bahmutov clarification on what you need for an example site would be appreciated 😄

**Comment by matinfo** [comment]
very interesting, let go!

**Comment by bahmutov** [comment]
@grantbdev as an example I would love to see a simple site with 2 pages, each loading its own code. The test could open the first page, then click on a link to go to the second page. The collected coverage object should show coverage for the code loaded on the first page and the code loaded on the second page

**Comment by grantbdev** [comment]
@bahmutov PR rebased and updated with testing sample code in this package's test suite if that is OK with you.

**Comment by 3590Duncan** [comment]
Any updates on when this could potentially be releasd?

**Comment by windmaomao** [comment]
I'm not sure this is the right place, but i found out the bug might be related to the following lines for `beforeEach`.

```
    // save reference to coverage for each app window loaded in the test
    cy.on('window:load', saveCoverageObject)

    // save reference if visiting a page inside a before() hook
    cy.window({ log: false }).then(saveCoverageObject)
```

If i have a test file with multiple tests

```
describe('Button component', () => {
  it('should display label', () => {
    mount(<Button />);
  });
  it('should ..', () => {
    mount(<Button />)
  })
```

What happens is that `window.__coverage__` does not get reset when going from the first `it` to the second `it`. So when combining them, it gets a weird behavior, for example, all the counts in the second `it` would carry all the counts in the first `it` already.

**Pull request merged**
