### PR TITLE
fix: Fix error when testing cross-origin code

### PR DESCRIPTION
**Pull request by Nojay-Games**
- Closes https://github.com/cypress-io/code-coverage/issues/782

When testing cross-origin websites with `cy.origin()`, the following error gets thrown:
`DOMException: Blocked a frame with origin "http://localhost:3000" from accessing a cross-origin frame.`
This occurs when accessing `win.__coverage__` in the code. Since you don't control cross-origin code and it therefore doesn't need code coverage, you can simply ignore the code coverage if accessing `win.__coverage__` throws an error.

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
@Nojay-Games Thanks for the contribution! Can you write a test to cover the logic for the fix you wrote?

**Comment by JRSalica** [comment]
That fix is what I need, there is no way to merge it into production so I can update the dependency solve the conflict I have with the library when doing my tests? thanks!

**Comment by jennifer-shehane** [comment]
@Nojay-Games Will you have time to write a test for this? If the PR is incomplete, we'll have to close this.

**Review by alecmestroni — APPROVED** [review]

**Comment by alecmestroni** [comment]
@jennifer-shehane logs are expired and i cannot understand whats wrong in tests, is ok for u to rerun the merge so we can see whats going wrong?

**Comment by jennifer-shehane** [comment]
@alecmestroni I pushed an empty commit. I believe the original ask was to write a test case that tests the added behavior here. Since there's nothing confirming this fixes the behavior or prevents regressions from being introduced.

**Comment by alecmestroni** [comment]
> @alecmestroni I pushed an empty commit. I believe the original ask was to write a test case that tests the added behavior here. Since there's nothing confirming this fixes the behavior or prevents regressions from being introduced.

Sadly its not an error during the test but its a permission bug related to the account used
```
Run snyk test --all-projects --detection-depth=4 --exclude=docker,Dockerfile,test-apps --severity-threshold=critical
`snyk` requires an authenticated account. Please run `snyk auth` and try again.
Error: Process completed with exit code 2.
```

**Comment by jennifer-shehane** [comment]
@alecmestroni Yah, the snyk failure can be ignored. It doesn't run properly for contributors.

**Comment by alecmestroni** [comment]
> @alecmestroni Yah, the snyk failure can be ignored. It doesn't run properly for contributors.

@jennifer-shehane  so tests are passing and merge can be applied

**Comment by jennifer-shehane** [comment]
@alecmestroni There is no test for the change in behavior here verifying the behavior at all.

**Comment by alecmestroni** [comment]
@jennifer-shehane test added https://github.com/Nojay-Games/code-coverage/pull/1

**Comment by alecmestroni** [comment]
Any news?

**Comment by alecmestroni** [comment]
@jennifer-shehane any news?

**Comment by jennifer-shehane** [comment]
@alecmestroni - @mschile is assigned to review this is he finds some extra time. Thanks for your patience.

**Comment by alecmestroni** [comment]
@jennifer-shehane he has done the changing. please approve them

**Comment by lhimstedt** [comment]
@Nojay-Games thank you for this one, I just found this problem and it's super annyoing! @alecmestroni and thank you for the tests! 

@jennifer-shehane could you push this?

**Comment by mschile** [comment]
@alecmestroni and @lhimstedt, the tests are failing, so I still need to investigate that before this PR can be merged.

**Review by mschile — APPROVED** [review]

**Review by cacieprins — APPROVED** [review]

**Pull request merged**
