### PR TITLE
feat: add explicit check against codeCoverage.expectFrontendCoverageOnly before attempting to collect backend coverage

### PR DESCRIPTION
**Pull request by funkadelic**
PR for https://github.com/cypress-io/code-coverage/issues/473. See https://github.com/cypress-io/code-coverage/issues/473 for details behind the change

### CODE REVIEW

**Comment by rsudarson** [comment]
Please release a version with this change. @maartencardinaels @funkadelic

**Comment by jogelin** [comment]
@funkadelic is this PR still planned? My monitoring is showing all of these failing requests...

**Comment by funkadelic** [comment]
@maartencardinaels thanks for the PR approval; is there anything else needed from my end to get this merged down to master & released?

**Comment by maartencardinaels** [comment]
> @maartencardinaels thanks for the PR approval; is there anything else needed from my end to get this merged down to master & released?

one of the project collaborators will have to merge this PR

**Comment by docwhite** [comment]
I forked from master and brought in the same changes @funkadelic has. Therefore the PR I created is an updated duplicate of this PR.

https://github.com/cypress-io/code-coverage/pull/555

**Pull request closed without merging**
